name: flutter_eco_mode_example
description: "Demonstrates how to use the flutter_eco_mode plugin."
publish_to: 'none'

version: 0.0.3

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_eco_mode:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true