name: flutter_eco_mode
description: "A Flutter plugin to help implementing custom eco-friendly mode in your mobile app."
version: 0.1.0
homepage: https://github.com/sncf-connect-tech/flutter_eco_mode

environment:
  sdk: '^3.7.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^26.1.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: sncf.connect.tech.flutter_eco_mode
        pluginClass: FlutterEcoModePlugin
      ios:
        pluginClass: FlutterEcoModePlugin